version: "3.8"
services:
  php:
    ports:
      - 8000:8000
    networks:
      - default

  db:
    ports:
      - 3307:3306
    networks:
      - default

  redis:
    ports:
      - 6379:6379
    networks:
      - default

