apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: larastorage
spec:
  selector:
    app: larastorage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
